[tools]
bun = "latest"
chezmoi = "latest"
go = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:markdownlint-cli2" = "latest"
python = "latest"
rust = "latest"
uv = "latest"

[settings]

[settings.npm]
package_manager = "bun"
